# Generated by Django 4.2.4 on 2023-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number_for_lead',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
