# Generated by Django 4.2.4 on 2023-08-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_maincategory_zipcode_subcategory_servicecategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyzipmodel',
            name='company',
        ),
        migrations.CreateModel(
            name='RadiusZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_zip', models.IntegerField(blank=True, null=True)),
                ('radius_miles', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='companyzipmodel',
            name='radius_zip_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.radiuszipcode'),
        ),
    ]
